# Generated by Django 4.1.7 on 2023-06-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="track",
            fields=[
                (
                    "waybill",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("pickup", models.DateField()),
                ("origin", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("EDD", models.DateField()),
                ("phone", models.CharField(max_length=15)),
                ("receiver", models.CharField(max_length=50)),
                ("lastscan", models.CharField(max_length=50)),
            ],
        ),
    ]
